name:                core-implementations
version:             0.1.0.0
github:              "nbardiuk/core-lang"
license:             BSD3
author:              "Nazarii Bardiuk"
maintainer:          "nazarii@bardiuk.com"
copyright:           "2019 Nazarii Bardiuk"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  core-implementations-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-implementations

tests:
  core-implementations-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-implementations
